### ISSUE TITLE
Version 1.1 Issues

### ISSUE THREAD

**Issue by adelando** [Ethenski/Civitas#4] opened 2021-04-07 23:03 UTC
Hello,

The following are a few bugs i have found so far

- Unable to adjust day time length in global settings

- unable to select current world player is in to be allowed in Civitas global settings (can select other worlds just not the current world player is in, but works when moving to another world)

_(Also is multi world claiming for towns still coming in the future? or just an optional setting?)_

Thanks!

**Comment by Ethenski** [comment] 2021-04-08 19:33
> Unable to adjust day time length in global settings

I'm not experiencing this issue, the input system was cleaned up in 1.2.1, see if it works then.

> Unable to select current world player is in to be allowed in Civitas global settings (can select other worlds just not the current 
world player is in, but works when moving to another world)

This is intended as Civitas is already enabled in the world you're in (as you're able to open the configuration menu) - If you want to disable Civitas in your current world, you should move to another world first, then disable the previous world.

> Is multi world claiming for towns still coming in the future

I'll look into this but I can't promise this as a feature. Plots are suppose to belong to the world the respective Town belongs to, this might also cause conflicts with the anti-grief and war systems. However this shouldn't be impossible to fix.

**Comment by adelando** [comment] 2021-04-09 00:12
Update 1.2.1

> Unable to adjust day time length in global settings
Still unable to adjust time in 1.2.1
I have since made a fresh server with minimal plugins and cleared all civitas files and still won't accept any input.
It goes to ask me for input but when i put in say "86400" it doesn't accept it

![2021-04-09_08 05 14](https://user-images.githubusercontent.com/11265974/114110720-c6dc9680-990a-11eb-8e1a-d922021aef93.png)

![2021-04-09_07 34 59](https://user-images.githubusercontent.com/11265974/114110950-5124fa80-990b-11eb-8104-a99d92e330f0.png)

![2021-04-09_08 05 22](https://user-images.githubusercontent.com/11265974/114110734-c93ef080-990a-11eb-8b21-0b3eeb18e1c5.png)

**Comment by Ethenski** [comment] 2021-06-03 05:01
Tested again and can't seem to reproduce the issue. Can you send me the log files?

**Comment by adelando** [comment] 2021-06-03 09:26
Hmm I can’t seem to fault this now, I’m thinking it was an issue that was part of the chat plugin that has since updated and fixed the issue

**Comment by Ethenski** [comment] 2021-06-11 00:18
> Hmm I can’t seem to fault this now, I’m thinking it was an issue that was part of the chat plugin that has since updated and fixed the issue

**Closed by Ethenski** 2021-06-11 00:18 UTC
Labels: bug, question
